### ISSUE TITLE
cd-hit integration

### ISSUE THREAD

**Issue by HadrienG** [HadrienG/wiz#1]
after having downloaded the clad of interest, the `phylogeny` module should run cd-hit of the bin and the downloaded genomes

- [ ] create conda env (waiting for #2 )
- [ ] add cd-hit as dependency (waiting for #2)
- [ ] find proteins in bins (#12)
- [ ] run cd-hit
- [ ] save unique clustered (core?) proteins
